core/urls.py
from django.conf.urls import url
from django.contrib import auth
from core import forms
import core.views
import django.contrib.auth.views

urlpatterns = [
    url(r'^team/create/', core.views.create_team, name = 'team/create'),
    url(r'^team/', core.views.team, name = 'team'),
    url(r'^login/$', auth.views.login, {'template_name' : 'core/login.html', 'authentication_form' : forms.AuthenticationForm }, name='login'),
    url(r'^logout/$', auth.views.logout, { 'template_name' : 'core/logout.html' }, name='logout'),
    url(r'^control/start', core.views.control_start, name = 'control/start'),
    url(r'^control/', core.views.control, name = 'control'),
    url(r'^wait/', core.views.wait_to_start, name = 'wait'),
    url(r'^entity_detail/(\d+)', core.views.entity_detail, name = 'entity_detail'),
    url(r'^messages/', core.views.messages, name='messages'),
    url(r'^messages-standalone/', core.views.messages_standalone),
    url(r'^inventory/', core.views.inventory, name='inventory'),
    url(r'^entities/', core.views.entity_list, name='entities'),
    url(r'^$', core.views.router, name = 'router'),
]

ekonomicka/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import auctions.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes.urls', namespace="recipes")),
    url(r'^tokens/', include('tokens.urls', namespace="token")),
    url(r'^auction/', include('auctions.urls')),
    url(r'^blackmarket/', auctions.views.black_market, name='black'),
    url(r'^', include('core.urls')),
]

tokens/urls.py
from django.conf.urls import url
import tokens.views

urlpatterns = [
    url(r'^print$', tokens.views.token_print, name='print'),
    url(r'^$', tokens.views.token_input, name='input'),
]

tokens/models.py
import string

import random

import timedelta
from django.core import validators
from django.db import models, transaction

from core.models import Entity, Team, Transaction, Status, Game


class Token(models.Model):
    LENGTH = 6
    CONSONANTS="QWRTPSDFGHJKLZXCVBNM"
    VOWELS="AEIOUY"

    code = models.CharField(max_length=LENGTH, validators=[
        validators.RegexValidator("([%s][%s]){%d}[%s]{%d}" % (CONSONANTS, VOWELS, LENGTH / 2, CONSONANTS, LENGTH % 2))],
                            primary_key=True)
    entity = models.ForeignKey(Entity)
    used_by = models.ForeignKey(Team, null=True, blank=True, default=None)
    used_time = timedelta.TimedeltaField(null=True, blank=True, default=None)

    value = models.PositiveIntegerField(default=1)

    @transaction.atomic
    def _use_commit(self, team):
        # You can't simply add to balance, as there may be some constraints (e.g. licences)
        with Transaction() as t:
            t.add(team, self.entity, self.value)

        self.used_by = team
        self.used_time = Game.game_time()
        self.save()

    def use(self, team: Team):
        if self.used_by is not None:
            if self.used_by == team:
                raise TokenUnusableException("Tento kód už jsi použil.")
            else:
                Status.add("Tým %s přinesl kód, který už použil tým %s. Mají co vysvětlovat!" % (team, self.used_by), Status.DANGER, self.used_by)
                raise TokenUnusableException("Tento kód už použil tým %s. Myslím, že je čas zajít za organizátory!" % self.used_by)

        return self._use_commit(team)

    @staticmethod
    def get(code: str):
        return Token.objects.get(code=code.upper())

    @staticmethod
    def randomcode():
        return "".join(random.choice(Token.VOWELS if i % 2 == 1 else Token.CONSONANTS) for i in range(Token.LENGTH))

    @staticmethod
    def generate_one(entity: Entity, amount=1):
        t = Token(entity=entity, code=Token.randomcode(), value=amount)
        t.save()
        return t

    def __repr__(self):
        return "<Token: %s>" % self.code

class TokenUnusableException(Exception):
    pass

tokens/views.py
import random
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect

from core.models import InvalidTransaction
from ekonomicka.utils import team_required, game_running_required
from tokens.models import Token, TokenUnusableException


class TokenForm(forms.Form):
    code = forms.CharField(min_length=Token.LENGTH, max_length=Token.LENGTH, label="Kód lístečku:")

@team_required
@game_running_required
def token_input(request):
    if request.method == 'POST':
        try:
            f = TokenForm(request.POST)
            if f.is_valid():
                token = Token.get(f.cleaned_data['code'])
                token.use(request.team)
                messages.add_message(request, messages.SUCCESS, "Našel jsi %s!" % token.entity)
                return redirect("token:input")
        except Token.DoesNotExist:
            messages.add_message(request, messages.INFO, "Takový lísteček neexistuje!")
        except (InvalidTransaction, TokenUnusableException) as e:
            messages.add_message(request, messages.WARNING, "%s" % e)
    else:
        f = TokenForm()

    return render(request, "tokens/input.html", {'form': f})

@permission_required("game_control")
def token_print(request):
    tok = list(Token.objects.all())
    random.shuffle(tok)
    return render(request, "tokens/print.html", {
        'tokens': tok
    })

templates/tokens/input.html
{% extends "base.html" %}
{%  load bootstrap %}
{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <form action="{% url "token:input" %}" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
        </form>
    </div>
</div>

<script>

window.onload = function() {
    $("#id_code").focus();
};
</script>
{% endblock %}

templates/tokens/print.html
{% load utils static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Print lístečků</title>
    <style>
        .token {
            display: inline-block;
            margin: 0;
            padding: 7px 0;
            box-sizing: border-box;
            border-top: 1px dotted black;
            border-left: 1px dotted black;
            font: 20px "Source Code Pro";
            width: 85px;
            height: 96px;
        }

        .token span {
            display: block;
            text-align: center;
        }

        .token i {
            display: block;
            margin: 5px auto;
        }
    </style>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "css/sprites.css" %}">
</head>
<body>
{% for t in tokens %}<div class="token">
        {{ t.entity|entity_icon_nolink }}
        <span>{{ t.code }}</span>
    </div>{% endfor %}
</body>
</html>