core/urls.py
from django.conf.urls import url
from django.contrib import auth
from core import forms
import core.views
import django.contrib.auth.views

urlpatterns = [
    url(r'^team/create/', core.views.create_team, name = 'team/create'),
    url(r'^team/', core.views.team, name = 'team'),
    url(r'^login/$', auth.views.login, {'template_name' : 'core/login.html', 'authentication_form' : forms.AuthenticationForm }, name='login'),
    url(r'^logout/$', auth.views.logout, { 'template_name' : 'core/logout.html' }, name='logout'),
    url(r'^control/start', core.views.control_start, name = 'control/start'),
    url(r'^control/', core.views.control, name = 'control'),
    url(r'^wait/', core.views.wait_to_start, name = 'wait'),
    url(r'^entity_detail/(\d+)', core.views.entity_detail, name = 'entity_detail'),
    url(r'^messages/', core.views.messages, name='messages'),
    url(r'^messages-standalone/', core.views.messages_standalone),
    url(r'^inventory/', core.views.inventory, name='inventory'),
    url(r'^entities/', core.views.entity_list, name='entities'),
    url(r'^$', core.views.router, name = 'router'),
]

ekonomicka/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import auctions.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes.urls', namespace="recipes")),
    url(r'^tokens/', include('tokens.urls', namespace="token")),
    url(r'^auction/', include('auctions.urls')),
    url(r'^blackmarket/', auctions.views.black_market, name='black'),
    url(r'^', include('core.urls')),
]

recipes/urls.py
from django.conf.urls import url

from . import views

app_name = "recipes"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/([0-9]+)', views.detail, name='detail')
]

tokens/urls.py
from django.conf.urls import url
import tokens.views

urlpatterns = [
    url(r'^print$', tokens.views.token_print, name='print'),
    url(r'^$', tokens.views.token_input, name='input'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/main.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/sprites.css' %}" rel = "stylesheet">
    <title>{% block title %}praAukro{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'router' %}">praAukro</a>
    </div>
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar">
            {% if user.is_authenticated %}
                <li><a href="{% url 'team' %}" class="navbar-">Inventář</a></li>
                <li><a href="{% url 'auction/list' %}">Aukce</a></li>
                <li><a href="{% url 'black' %}" class="active">Černý trh</a></li>
                <li><a href="{% url 'entities' %}">Předměty</a></li>
                <li><a href="{% url 'recipes:index' %}">Recepty</a></li>
                <li><a href="{% url 'token:input' %}">Zadávání lístečků</a></li>
                {% if perms.core.control_game  %}
                <li><a href="{% url 'control' %}">Ovládací panel</a></li>
                <li><a href="/admin">Administrace</a></li>
                {% endif %}
                <li><a href="{% url 'messages' %}">Zprávy</a></li>
                <li><a href="{% url 'inventory' %}">Stavy týmů</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-right navbar-nav">
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Odhlásit</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Přihlásit se</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/ekonomicka.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>