core/urls.py
from django.conf.urls import url
from django.contrib import auth
from core import forms
import core.views
import django.contrib.auth.views

urlpatterns = [
    url(r'^team/create/', core.views.create_team, name = 'team/create'),
    url(r'^team/', core.views.team, name = 'team'),
    url(r'^login/$', auth.views.login, {'template_name' : 'core/login.html', 'authentication_form' : forms.AuthenticationForm }, name='login'),
    url(r'^logout/$', auth.views.logout, { 'template_name' : 'core/logout.html' }, name='logout'),
    url(r'^control/start', core.views.control_start, name = 'control/start'),
    url(r'^control/', core.views.control, name = 'control'),
    url(r'^wait/', core.views.wait_to_start, name = 'wait'),
    url(r'^entity_detail/(\d+)', core.views.entity_detail, name = 'entity_detail'),
    url(r'^messages/', core.views.messages, name='messages'),
    url(r'^messages-standalone/', core.views.messages_standalone),
    url(r'^inventory/', core.views.inventory, name='inventory'),
    url(r'^entities/', core.views.entity_list, name='entities'),
    url(r'^$', core.views.router, name = 'router'),
]

ekonomicka/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import auctions.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes.urls', namespace="recipes")),
    url(r'^tokens/', include('tokens.urls', namespace="token")),
    url(r'^auction/', include('auctions.urls')),
    url(r'^blackmarket/', auctions.views.black_market, name='black'),
    url(r'^', include('core.urls')),
]

recipes/urls.py
from django.conf.urls import url

from . import views

app_name = "recipes"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/([0-9]+)', views.detail, name='detail')
]

recipes/models.py
from django.db import models
from core.models import *


class Recipe(models.Model):
    name = models.TextField()
    description = models.TextField()

    def ingredients(self):
        """
        Transforms ingredients to lists of Quantities
        """
        needs = []
        creates = []
        consumes = []

        for ingredient in Ingredient.objects.filter(recipe=self):
            arr = []
            if ingredient.type == Ingredient.NEED:
                arr = needs
            elif ingredient.type == Ingredient.CREATE:
                arr = creates
            elif ingredient.type == Ingredient.CONSUME:
                arr = consumes
            else:
                assert False

            arr.append(Quantity(ingredient.entity, ingredient.amount))

        return (needs, creates, consumes)

    def perform(self, team, pretend=False):
        """
        Apply the recipe for the team.
        :raises ValidationError when there is not enough entities
        """
        (needs, creates, consumes) = self.ingredients()
        with Transaction() as t:
            for q in needs:
                t.needs(team, q.entity, q.amount)
            for q in consumes:
                t.remove(team, q.entity, q.amount)
            team.assert_valid()
            for q in creates:
                t.add(team, q.entity, q.amount)

            if pretend:
                t.clean()
                t.abort()

    def can_perform(self, team):
        """ Returns True when a team can perform the recipe """
        try:
            self.perform(team, pretend=True)
            return True
        except:
            return False

    def __str__(self):
        return "%s: %s" % (self.name, self.description)


class Ingredient(models.Model):
    CONSUME = 0
    NEED = 1
    CREATE = 2
    TYPES = (
        (CONSUME, "Consumes"),
        (NEED, "Needs"),
        (CREATE, "Creates"),
    )
    recipe = models.ForeignKey(Recipe)
    entity = models.ForeignKey(Entity)
    type = models.PositiveSmallIntegerField(choices=TYPES)
    amount = models.IntegerField()

    class Meta:
        unique_together = ("recipe", "entity", "type")

recipes/forms.py
from django.contrib import auth
import django.contrib.auth.forms
from django import forms

class PerformRecipeForm(forms.Form):
    pass

recipes/views.py
from django.shortcuts import render

from core.models import Quantity, Balance, Team, InvalidTransaction
from ekonomicka.utils import team_required
from recipes.forms import PerformRecipeForm
from recipes.models import Recipe


# Wrapper class for recipes, its ingredients
class RecipeIngred:
    def __init__(self, recipe: Recipe, team:Team):
        self.recipe = recipe
        self.can_perform = recipe.can_perform(team)
        (self.needs, self.creates, self.consumes) = recipe.ingredients()


@team_required
def index(request):
    recipes = [ recipe for recipe in Recipe.objects.all() ]
    team = request.user.player.team

    recipes_ingred = []
    for recipe in recipes:
        ri = RecipeIngred(recipe, team)
        recipes_ingred.append(ri)

    recipes_ingred.sort(key=lambda recipe_ingred: not recipe_ingred.can_perform)

    return render(request, "recipes/index.html", { 'recipes_ingred' : recipes_ingred })


@team_required
def detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    team = request.user.player.team

    recipe_ingred = RecipeIngred(recipe, team)

    performed = False
    if request.method=="POST":
        recipe.perform(team)
        performed = True

    errors = ""
    is_possible = False
    try:
        recipe.perform(team, pretend=True)
        is_possible = True
    except InvalidTransaction as e:
        errors = str(e)




    return render(request, "recipes/detail.html", {
        'recipe_ingred':recipe_ingred,
        'is_possible':is_possible,
        'errors':errors,
        'form':PerformRecipeForm(),
        'performed':performed,
        'balance': request.team.balance_set.all(),
    })

templates/recipes/detail.html
{% extends "base.html" %}
{% block title %}Recept {{ recipe.name }}{% endblock %}
{% block content %}

    {% if performed %}
        <div class="alert alert-success">Recept byl proveden</div>
    {% endif %}

    <h2>{{ recipe_ingred.recipe.name }}</h2>

    <p>{% include "recipes/recipe_line.html" with recipe_ingred=recipe_ingred %}</p>

    <h3>Provedení receptu</h3>
    {% if is_possible %}
        <form method="post">
        {{ form }}
        {% csrf_token %}
        <button type="submit" class="button">Proveď recept</button>
        </form>
    {% else %}
        <div class="alert alert-warning">
            Nelze provést recept: {{ errors }}
        </div>
    {% endif %}

    <h3>Váš inventář</h3>
    {% include "core/team_inventory.html" %}

{% endblock %}

templates/recipes/index.html
{% extends "base.html" %}
{% block title %}Recepty{% endblock %}
{% block content %}
    {% for recipe_ingred in recipes_ingred %}
        <div class="well well-sm recipe-{% if not recipe_ingred.can_perform %}non{% endif %}performable"
             style="padding-top: 0; padding-bottom: 0">
            <h3 style="margin-top: 15px">
                <a href="{% url 'recipes:detail' recipe_ingred.recipe.id %}">{{ recipe_ingred.recipe.name }}</a>
            </h3>
            <p>
                {% include "recipes/recipe_line.html" with recipe_ingred=recipe_ingred %}
            </p>
        </div>
    {% endfor %}

{% endblock %}

templates/recipes/quantity_list.html
{% load utils %}

{% for quantity in quantities %}
    {{ quantity.amount|quantity:quantity.entity }}
{%  endfor %}

templates/recipes/recipe_line.html
{% include "recipes/quantity_list.html" with quantities=recipe_ingred.consumes %}
⟶
{% if recipe_ingred.needs|length > 0 %}
    [<i>
    {% include "recipes/quantity_list.html" with quantities=recipe_ingred.needs %}
</i>]
    ⟶
{% endif %}
{% include "recipes/quantity_list.html" with quantities=recipe_ingred.creates %}